# Generated by Django 5.0.1 on 2024-03-12 19:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonemodel',
            name='mileStoneContent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
