# Generated by Django 3.2.5 on 2021-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='validtill',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
