# Generated by Django 5.0.1 on 2024-03-29 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPMS', '0003_alter_proposalmodel_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmodel',
            name='assignedTo',
            field=models.ManyToManyField(related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
