# Generated by Django 5.0.1 on 2024-04-04 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPMS', '0007_alter_proposalmodel_assignedto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalmodel',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='proposalmodel',
            name='assignedTo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
