# Generated by Django 5.0.1 on 2024-04-04 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPMS', '0008_remove_proposalmodel_assignedto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='assignedTo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to=settings.AUTH_USER_MODEL),
        ),
    ]
